// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Videos.Data;

#nullable disable

namespace Videos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220923124458_Migración inicial tabla videos")]
    partial class Migracióninicialtablavideos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Videos.Models.Video", b =>
                {
                    b.Property<int>("id_videos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_videos"), 1L, 1);

                    b.Property<string>("etag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_videos");

                    b.ToTable("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
